# Generated by Django 4.1 on 2022-08-07 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255)),
                ('cor', models.CharField(default='#000', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255)),
                ('descricao', models.TextField(default='', max_length=144)),
                ('url', models.CharField(default='', max_length=1000)),
                ('privado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='videos.categoria')),
            ],
        ),
    ]
