# Generated by Django 4.1 on 2022-08-07 00:41

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(default=videos.models.Video.default, on_delete=django.db.models.deletion.CASCADE, to='videos.categoria'),
        ),
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
