# Generated by Django 4.1 on 2022-08-07 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_privado_video_gratis_alter_video_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='gratis',
            new_name='premium',
        ),
    ]
